#██╗░░░░░███████╗██╗░░░██╗███████╗██╗░░░░░████████╗░█████╗░░█████╗░██╗░░░░░░██████╗
#██║░░░░░██╔════╝██║░░░██║██╔════╝██║░░░░░╚══██╔══╝██╔══██╗██╔══██╗██║░░░░░██╔════╝
#██║░░░░░█████╗░░╚██╗░██╔╝█████╗░░██║░░░░░░░░██║░░░██║░░██║██║░░██║██║░░░░░╚█████╗░
#██║░░░░░██╔══╝░░░╚████╔╝░██╔══╝░░██║░░░░░░░░██║░░░██║░░██║██║░░██║██║░░░░░░╚═══██╗
#███████╗███████╗░░╚██╔╝░░███████╗███████╗░░░██║░░░╚█████╔╝╚█████╔╝███████╗██████╔╝
#╚══════╝╚══════╝░░░╚═╝░░░╚══════╝╚══════╝░░░╚═╝░░░░╚════╝░░╚════╝░╚══════╝╚═════╝░
settings:
  #What to replace the %xp_needed% placeholder with once the user has reached max level
  maxLevel: "&a&lMAX"


progressbar:
  filler: "|"
  bars: 10
  incomplete_color: "c"
  complete_color: "a"


pickaxe:
  enabled: true
  lore:
    - "&7Blocks: &b%blocks%"
    - "&7Level: &b%level% &8(&a%percentage%%&8)"
    - "&7XP: &c%xp% / %xp_needed%"
    - "&7Progress: &8[%progressbar%&8]"

  #How much XP each block should give?
  blocks:
    - STONE:1
  disabled_worlds:
    - "example"

  levels:
    1:
      xp-needed: 0
      rewards:
        - "[cmd] eco give %player% 100"
        - "[message] &bCongrats %player% you have reached level 1 on your pickaxe"
        - "[enchant] DIG_SPEED 1"
    2:
      xp-needed: 100
      rewards:
        - "[cmd] eco give %player% 200"


axe:
  enabled: true
  lore:
    - "&7Blocks: &b%blocks%"
    - "&7Level: &b%level% &8(&a%percentage%%&8)"
    - "&7XP: &c%xp% / %xp_needed%"
    - "&7Progress: &8[%progressbar%&8]"

  #How much XP each block should give?
  blocks:
    - OAK_LOG:1
  disabled_worlds:
    - "example"

  levels:
    1:
      xp-needed: 0
      rewards:
        - "[cmd] eco give %player% 100"
        - "[message] &bCongrats %player% you have reached level 1 on your axe"
        - "[enchant] DIG_SPEED 1"
    2:
      xp-needed: 100
      rewards:
        - "[cmd] eco give %player% 200"

shovel:
  enabled: true
  lore:
    - "&7Blocks: &b%blocks%"
    - "&7Level: &b%level% &8(&a%percentage%%&8)"
    - "&7XP: &c%xp% / %xp_needed%"
    - "&7Progress: &8[%progressbar%&8]"

  #How much XP each block should give?
  blocks:
    - GRASS_BLOCK:2
      - DIRT:1
  disabled_worlds:
    - "example"

  levels:
    1:
      xp-needed: 0
      rewards:
        - "[cmd] eco give %player% 100"
        - "[message] &bCongrats %player% you have reached level 1 on your shovel"
        - "[enchant] DIG_SPEED 1"
    2:
      xp-needed: 100
      rewards:
        - "[cmd] eco give %player% 200"

#PVP ITEMS
sword:
  enabled: true
  onlyplayerdamage: false
  lore:
    - "&7DAMAGE: &c%damage% / %damage_needed%"
    - "&7Level: &b%level% &8(&a%percentage%%&8)"
    - "&7Progress: &8[%progressbar%&8]"

  disabled_worlds:
    - "example"

  levels:
    1:
      damage-needed: 0
      rewards:
        - "[cmd] eco give %player% 100"
        - "[message] &bCongrats %player% you have reached level 1 on your sword"
        - "[enchant] DAMAGE_ALL 1"
    2:
      damage-needed: 100
      rewards:
        - "[cmd] eco give %player% 200"

bow:
  enabled: true
  onlyplayerdamage: false
  lore:
    - "&7DAMAGE: &c%damage% / %damage_needed%"
    - "&7Level: &b%level% &8(&a%percentage%%&8)"
    - "&7Progress: &8[%progressbar%&8]"

  disabled_worlds:
    - "example"

  levels:
    1:
      damage-needed: 0
      rewards:
        - "[cmd] eco give %player% 100"
        - "[message] &bCongrats %player% you have reached level 1 on your bow"
        - "[enchant] POWER 1"
    2:
      damage-needed: 100
      rewards:
        - "[cmd] eco give %player% 200"

#1.16+ items can be configured below this line
#If you are on 1.8 leave everything below here disabled
crossbow:
  enabled: false
  onlyplayerdamage: false
  lore:
    - "&7DAMAGE: &c%damage% / %damage_needed%"
    - "&7Level: &b%level% &8(&a%percentage%%&8)"
    - "&7Progress: &8[%progressbar%&8]"

  disabled_worlds:
    - "example"

  levels:
    1:
      damage-needed: 0
      rewards:
        - "[cmd] eco give %player% 100"
        - "[message] &bCongrats %player% you have reached level 1 on your crossbow"
        - "[enchant] POWER 1"
    2:
      damage-needed: 100
      rewards:
        - "[cmd] eco give %player% 200"