name: LevelTools
version: 2.0.3
main: me.Hayden.LevelTools.Main
softdepend: [ AutoSell, VKAutoPickup, TokenEnchant, AdvancedEnchantments ]
api-version: 1.13
commands:
  leveltools:
    description: main command